### ISSUE TITLE
modularity?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [madox2/vim-ai#10]
Hello again!

I hope you're doing well. I have a question about 'g:vim_ai_chat' and how to customize the chat window. I'm wondering if there's a way to make it more flexible so that users can choose how to open the chat window. For example, could we add some arguments to the shortcut input so that users can choose between opening the chat window in a split or a new tab?

I'm a total noob at vimscript, so I might be missing something obvious. But I think it would be really helpful.

Also, just to give you an idea of what I'm talking about, when you added the "ui" key in 'g:vim_ai_chat', I wasn't sure if the intent was to make it easily customizable by the user as a 'setting' or as a modular type of code. Right now, it seems like I can only open the chat window as either a split or a new tab, but not both. Is there a way to make it more modular so that users can have more flexibility in how they open the chat window? For example, instead of the shortcut inputting ":AIChat<CR>", could we have it enter ":AIChat newtab<CR>" to make it easier for less savvy users to have a binding for ":AIChat split<CR>"?

Having at least one argument would make it easier I think for other users to customize it if they know python but no vimscript.

Thanks!

**Comment by madox2** [comment]
Hi, thanks for the feedback! I am planning to change the interface of `AIRun` (and other) functions in a way that it will be possible to pass options in it. I need to think it through as it will be a breaking change. Hope that it would make it modular as you requested.

In the meantime what you could do is to write a custom function that changes the settings and then triggers the chat.

**Comment by thiswillbeyourgithub** [comment]
> In the meantime what you could do is to write a custom function that changes the settings and then triggers the chat.

I unfortunately don't have the vimscript level to do that, or that would be quite tedious. I can wait any new versions no problem, though if you don't mind adding an example code as a comment that shows how to do that, it might be useful to me and others.

**Comment by thiswillbeyourgithub** [comment]
On second thought, the ability to specify the temperature also could be useful. You don't always need the same parameters after all.

I think a simple workflow would be to have commands like `:AiChat t=0.1 newtab<CR>` as a shortcut. This would make it very intuitive to customize : just change your shortcut for different needs.

**Comment by madox2** [comment]
You can modify any option by assigning a new value to it, for example `:let g:vim_ai_chat['options']['temperature'] = 0.5`. Here is how you could write a custom chat function:

```vim
function! AIChatCustom()
  let g:vim_ai_chat['options']['temperature'] = 0.5
  AIChat
endfunction
```

Anyway you got me thinking, it might make sense to override options per .aichat file. My initial thought is to put options to the top of the chat, it could look like this:

```
[options]
temperature=0.5
model=gpt-4

>>> user

generate a paragraph of lorem ipsum

<<< assistant

Sure, here's a paragraph of Lorem Ipsum:
```

**Comment by thiswillbeyourgithub** [comment]
Great idea! Thanks a lot

**Comment by madox2** [comment]
The configuration can be injected through the function parameters now, see https://github.com/madox2/vim-ai#custom-commands

**Comment by thiswillbeyourgithub** [comment]
I finally had the time to take a look. Thanks a lot for everything, it's great :)
