### ISSUE TITLE
prepend instead of append role instructions to prompt

### ISSUE THREAD

**Issue by Konfekt** [madox2/vim-ai#101]
Often, one gives instructions and code to the AIChat buffer and only then runs the `AIChat /role` command;
these are mostly understood to come before the specific instructions.
However, they are appended to the existing instructions

```
>>> user
What is the best Vim plug-in?
You are an all-knowing Vim wizard...
:
```

instead of prepended (this issue's suggestion)

```
>>> user
You are an all-knowing Vim wizard...
:
What is the best Vim plug-in?
```

 I suggest that the latter variant would be more natural.
For now, it requires jumping back to the beginning of the prompt.

However, if I recall correctly, there was some reluctance to label roles as such, so maybe these role prompts are meant to expect the instructions before them?

**Comment by Konfekt** [comment]
For what it's worth, maybe there's no need to paste the whole prompt into the aichat buffer, and a
```
>>> user (vim-wizard)
```
would do as well, but again, I faintly remember that, maybe for technical reasons, this was not such a good idea?

**Comment by madox2** [comment]
Just re-tested it and it had always been working as you suggested, it generates prompt like this:

```
>>> user

Your ar an all-knowing Vim wizard...:
what is the best vim plugin?
```
