### ISSUE TITLE
AIChat immediatelly sends out the query without waiting for my input

### ISSUE THREAD

**Issue by juodumas** [madox2/vim-ai#106]
This line introduced in the commit https://github.com/madox2/vim-ai/commit/17a914f628c2ac880cd1439199a9c1d4b16f0394 is causing `:AIChat` to immediately send out the query without waiting for my input:
https://github.com/madox2/vim-ai/blob/56dc5a54b118727881d225087ff3a20e5b0f6c79/autoload/vim_ai.vim#L87

I am running vim 9.1.0377 (Debian).

**Comment by Konfekt** [comment]
Yes, there's https://github.com/madox2/vim-ai/pull/94 and https://github.com/madox2/vim-ai/pull/96 to make up for it, but they weren't vetted yet

**Comment by madox2** [comment]
I am not sure how to reproduce. I tried all use cases and it works as before. Could you describe more what you did and what is actual and expected behavior?

**Comment by Konfekt** [comment]
What would be all use cases? I'd expect `&paste` to be pending if interrupting `:AIChat` output with `<c-c>`, say?

**Comment by juodumas** [comment]
Interesting, looks like this is caused by the following vimrc option after the aforementioned commit:
```
set formatoptions+=r " Insert mode: add comment char after hitting Enter
```

**Comment by Konfekt** [comment]
If one looks at

https://github.com/madox2/vim-ai/commit/17a914f628c2ac880cd1439199a9c1d4b16f0394#diff-c5343a5d13850471f849776609ce57fc060df53e28763bb19f8c407e81854970R181

then insert mode is entered with `normal! c` and in

```py
#  py/utils.py (lines 89-101)
def render_text_chunks(chunks, is_selection):
    generating_text = False
    full_text = ''
    insert_before_cursor = need_insert_before_cursor(is_selection)
    for text in chunks:
        if not text.strip() and not generating_text:
            continue # trim newlines from the beginning
        generating_text = True
        if insert_before_cursor:
            vim.command("normal! i" + text)
            insert_before_cursor = False
        else:
            vim.command("normal! a" + text)
```

lines are added.
Then `:help 'paste'` says also that

```
	These options keep their value, but their effect is disabled:
		- 'cindent'
		- 'formatoptions' is used like it is empty
		- 'indentexpr'
		- 'lisp'
		- 'smartindent'
```

so it is likely due to `paste` not being set properly.

**Comment by Konfekt** [comment]
Maybe solved by the latest commits?
