### ISSUE TITLE
Very Useful Tool

### ISSUE THREAD

**Issue by F1LT3R** [madox2/vim-ai#107]
Just here to drop a little praise.

This tool is super useful. And your documentation is written nicely. It was easy to set things up.

Thanks a bunch for putting this together!

I accidentally signed up for Chat-GPT, not Open-AI, so I got stuck there for a minute on the Pay as You Go message.

But that's related to the messaging on the Open-AI website, not your work.

The roles integration is fantastic. This will be a great help with writing.

Thanks again.

```ini
# chat-gpt-roles.ini
[synonym]
prompt = list about 10 synonyms

[antonym]
prompt = list about 10 antonyms

[rewrite]
prompt = rewrite this text

[rewrite_creative]
prompt = rewrite this text

[rewrite_creative.options]
temperature = 0.8
```

```vim
" .vimrc
xnoremap <leader>r :AI /rewrite<CR>
xnoremap <leader>r :AI /rewrite<CR>

nnoremap <leader>w :AI /rewrite_creative<CR>                                                                   
nnoremap <leader>w :AI /rewrite_creative<CR>

xnoremap <leader>a :AI /antonym<CR>
nnoremap <leader>a :AI /antonym<CR>

xnoremap <leader>s :AI /synonym<CR>
nnoremap <leader>s :AI /synonym<CR>
```

```markdown
dark                                                                                                           
1. Light
2. Bright
3. Clear
4. White
5. Radiant
6. Luminous
7. Shiny
8. Sunny
9. Brilliant
10. Glowing

The quick brown fox jumped over the lazy dog.                                                                  
The fast brown fox leaped over the sluggish dog
```

**Comment by F1LT3R** [comment]
Oh, one more thing...

It would be neat to have a global temperature control that showed up in the status line.

```
                                                                 👇
 NORMAL  README.md                                              °0.8 | unix | utf-8 | vim  100%  204:1
 ```
 
 And use  `<leader>=` and ` <leader>-` to raise and lower the temperature manually depending on the context of your writing.

**Comment by madox2** [comment]
Thank you for the kind words! Temperature in the status line sounds like a cool idea (I would only not add default shortcuts, but let user to configure it). Anyway, PRs are welcome :)
