### ISSUE TITLE
`paste` does not get reset back to `nopaste` after doing :AIChat

### ISSUE THREAD

**Issue by misterbuckley** [madox2/vim-ai#109]
I saw that `'paste'` gets set inside of the aichat buffers in order to get the formatting to work right. Unfortunately, it does not appear to get reset to `'nopaste'` after leaving the aichat buffer. I demonstrate this in the following recording:

[Screencast from 06-06-2024 09:57:54 PM.webm](https://github.com/madox2/vim-ai/assets/16565472/d66123be-720d-4ca0-a558-587766076cc2)

Here you can see the paste option is set to `'nopaste'` before I run `:AIChat`. After `:AIChat`, the paste option is set to `'paste'` both inside the aichat buffer _and_ in other buffers. Closing the aichat window also does not work to set paste ack to `'nopaste'`.

This is a problem for me because I normally have the autoindent option set. Setting `'paste'` disables autoindent, which is useful for the aichat window, but I would like it to be turned back on automatically after I'm done with the AIChat buffer.

Side note, `:setlocal paste` is not a "valid" vim command, since 'paste' is strictly a global option with no option to set it locally (see `:h option-summary` and `:h paste`), but this is a minor point since `:setlocal paste` still works to set it globally.

I am working on a solution, but wanted to put this out there in the meantime.

**Comment by misterbuckley** [comment]
I am working on a solution using `vim.command('put ...')` instead of going into insert mode to avoid the need to set `'paste'` entirely. Apparently I may be the only one experiencing this particular bug, so it may be a result of some peculiarity unique to my system, but as evidenced by #94 and #96, I am not the only one experiencing difficulty with the `'paste'` option in general. My fix may resolve those issues as well if paste is no longer needed. I will likely have this ready to go over the weekend.

**Comment by Konfekt** [comment]
Yes, there's https://github.com/madox2/vim-ai/pull/94 and https://github.com/madox2/vim-ai/pull/96 to make up for it, but they weren't vetted yet; would you mind testing them?

**Comment by Konfekt** [comment]
See also the discussion in https://github.com/madox2/vim-ai/issues/106

**Comment by Konfekt** [comment]
> Apparently I may be the only one experiencing this particular bug

You are not alone, that's why the PRs have been proposed

**Comment by madox2** [comment]
I just pushed functionality handling paste mode (https://github.com/madox2/vim-ai/commit/dac5aad10863d4ff7c00b349c59a3857f3bf8bd6, https://github.com/madox2/vim-ai/commit/9cd477a11e3044c1af59bc07a0bfc5b6094e912e, highly inspired by @Konfekt PRs). Please let me know if that resolved the issue.

@Konfekt is there anything else that we might be missing from #94 and #96 now?

**Comment by misterbuckley** [comment]
@madox2 The latest commits seem to have fixed the issue. Thank you!

**Comment by Konfekt** [comment]
@madox2 No, it only differs in, I'd suppose, negligible details
