### ISSUE TITLE
Invalid escape sequence in utils.py file

### ISSUE THREAD

**Issue by mmottl** [madox2/vim-ai#110]
I'm getting the following error when trying to invoke a chat:

```text
vim-ai/py/utils.py:234: SyntaxWarning: invalid escape sequence '\<'
```

Here is the affected function:

```python
def print_info_message(msg):
    vim.command("redraw")
    vim.command('call feedkeys("\<Esc>")')
    vim.command("echohl ErrorMsg")
    vim.command(f"echomsg '{msg}'")
    vim.command("echohl None")
```

**Comment by misterbuckley** [comment]
@mmottl This is being discussed on https://github.com/madox2/vim-ai/commit/f76aa3fdc4ac5f46145db8937bf10c04fa7c97dc - Can you try adding an `r` prefix to the string on the line with feedkeys (i.e. `vim.command(r'call feedkeys("\<Esc>")')`) and see if that fixes it for you?

**Comment by mmottl** [comment]
@misterbuckley Thanks, adding the `r` prefix worked for me (at least I don't see any error messages).
