### ISSUE TITLE
visual range select unexpected when use AIEdit 

### ISSUE THREAD

**Issue by cposture** [madox2/vim-ai#112]
For the most part, AIEdit works; but I found a problem in one case: if the cursor is on the c of "abc", using AIEdit on vi "will affect the entire line. I found that the following code is always 0 in this case.

```vim
    autocmd CursorMoved *
          \ let g:vim_ai_is_selection_pending = mode() =~# "^[vV\<C-v>]"
```

 @madox2 @Konfekt

**Comment by Konfekt** [comment]
Did the cursor move? Can you give the entire line?

**Comment by cposture** [comment]
Uploading 录屏2024-07-22 下午7.39.33.mov…

**Comment by cposture** [comment]
https://github.com/user-attachments/assets/b4c24576-fe0f-4296-82d8-13b308968b68

**Comment by cposture** [comment]
@Konfekt

**Comment by Konfekt** [comment]
I cannot reproduce. Selecting `"bbb"` in the line reading

```
aaa"bbb"ccc
```

and entering `'<,'>AIEdit replace by synonym` called 

```
" autoload/vim_ai.vim (lines 114-115)
function! s:GetVisualSelection()
  echoerr 1
```

as the error message showed and replaced the text with

```
aaa"Sorry, I couldn't find any synonyms for "bbb". Could you please provide more context or clarify the expression?"ccc
```

**Comment by cposture** [comment]
There is an important point here, the cursor needs to be located one letter before the second ", otherwise there is no problem @Konfekt

**Comment by Konfekt** [comment]
Yes, true, thank you for the reminder, though here it does not affect the result, the output is the same as above. Could you give a minimal [vimrc](https://github.com/vim/vim/issues/15152#issuecomment-2212354928) ?

**Comment by cposture** [comment]
The smallest vimrc can't be reproduced. It may be my vimrc problem. I'll find my own problem first. @Konfekt

**Comment by cposture** [comment]
```vim
set nocompatible
let &rtp = '/vim-ai/' . ',' . &rtp
set signcolumn=yes
filetype plugin indent on
syntax on
```
[2024-07-22 下午8.48.08.mov.zip](https://github.com/user-attachments/files/16333437/2024-07-22.8.48.08.mov.zip)

**Comment by cposture** [comment]
Are you using 「vi"」 to select? @Konfekt

**Comment by Konfekt** [comment]
> Are you using 「vi"」 to select? @Konfekt

Okay, here's how to reproduce: Put the cursor on the last letter of the letters surrounded by `"` and `"` and type `vi"`. Then the cursor does not move and the selection is not correctly recognized.

I don't see an obvious solution, since the autocmd hinging on CursorMove must fail, and other more suitable approaches failed: https://github.com/madox2/vim-ai/pull/77#issuecomment-1965216792
