### ISSUE TITLE
AIEdit and AI  Command Returns "Invalid 'messages': empty array" Error

### ISSUE THREAD

**Issue by Enrico68** [madox2/vim-ai#129]
#### Description
I am currently using the plugin  to interact with LiteLLM models. While the `:AIChat` command functions correctly, I am facing an issue with the `:AIEdit` and `AI` command. It returns an error indicating that the `messages` array is empty, which prevents the command from executing successfully.

#### Steps to Reproduce
1. **Set up the LiteLLM server**:
   ```sh
   litellm --model gpt-4o-mini
   ```
2. **Vim Configuration**: I have set up my Vim configuration with the following parameters:
   ```vim
   let g:vim_ai_edit = {
   \  "engine": "complete",
   \  "options": {
   \    "model": "gpt-4o-mini",
   \    "endpoint_url": "http://localhost:4000/v1/chat/completions",
   \    "max_tokens": 3000,
   \    "temperature": 0.1,
   \    "request_timeout": 20,
   \    "enable_auth": 0,
   \    "selection_boundary": "#####",
   \  },
   \  "ui": {
   \    "paste_mode": 1,
   \  },
   \}
   ```
3. **Use the Command**: I select a piece of text in Vim and run the AIEdit command:
   ```vim
   :AIEdit
   ```
or 

```
AI bla blal bla 
```

#### Error Message
Upon running the command, I receive the following error:
```
09:41:24 - LiteLLM:ERROR: main.py:411 - litellm.acompletion(): Exception occurred - Error code: 400 - {'error': {'message': "Invalid 'messages': empty array. Expected an array with minimum length 1, but got an empty array instead.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'empty_array'}}
```

#### Additional Context
- The `:AIChat` command works perfectly and handles conversations without any issues.
- The LiteLLM server is set up to run on `http://localhost:4000/v1/chat/completions`.
- I verified that the selected text is not empty before invoking the `:AIEdit` command.

#### Questions
1. What could be the reason for the `messages` array being empty during the `AIEdit` process?
2. Is there additional configuration I need to implement for `AIEdit` to work correctly?
3. Are there known limitations or issues with the current version of the plugin related to the `AIEdit` functionality?

Thank you for your assistance!

**Comment by madox2** [comment]
AI/AIEdit uses [legacy Completions API](https://platform.openai.com/docs/guides/completions). But I think it would be better now to migrate it to the `chat/completions` by default.

In the meantime, configuring chat engine manually should work for you: https://github.com/madox2/vim-ai?tab=readme-ov-file#using-chat-engine-for-completion-and-edits

**Comment by Enrico68** [comment]
Hi, 
The chat engine works without problem, just it is not practical for the use we need in VIM 😄 
Anyway thanks for your quick answer

**Comment by madox2** [comment]
You can configure AI/AIEdit to use chat endpoint - it will not behave like a chat in VIM, it will only use chat models behind the scenes

**Comment by Enrico68** [comment]
🆗
