### ISSUE TITLE
persistent aichat files solution no longer works 

### ISSUE THREAD

**Issue by nathanbraun** [madox2/vim-ai#130]
I've been using this function (modified slightly) by @GordianDziwis in the comment referenced [here](https://github.com/madox2/vim-ai/issues/28#issuecomment-1538156118) for a while now.  However, I just updated vim-ai and it no longer works.

Specifically when I run it creates a new buffer, but it doesn't appear to be really creating a new, persistent aichat file -- when I try to save it I get an error about `buftype=nofile`.  Any ideas on what may have changed?

```
let g:vim_ai_mod = {}
let g:vim_ai_mod['chat_files_path'] = '~/cloud/projects/chatgpt/chats-vim-ai/'
let g:vim_ai_open_chat_presets = {
\  'preset_below': 'below new | call vim_ai#MakeScratchWindow()',
\  'preset_tab': 'tabnew | call vim_ai#MakeScratchWindow()',
\  'preset_right': 'rightbelow 55vnew | setlocal noequalalways | setlocal winfixwidth | call vim_ai#MakeScratchWindow()',
\  'preset_persistent': 'call g:vim_ai_mod.CreatePersistentChat()'
\}

function! g:vim_ai_mod.CreatePersistentChat()
  let l:unique_id = system('uuidgen')
  let l:timestamp = strftime('%Y-%m-%d-%H-%M-%S')
  let l:filename = l:timestamp . '-' . printf('%.8s', l:unique_id) . '.aichat'
  execute 'e' g:vim_ai_mod['chat_files_path'] . l:filename
  setlocal filetype=aichat
endfunction
command! AINewPersistentChat call vim_ai#AINewChatRun('persistent')
```

**Comment by GordianDziwis** [comment]
I do not use vim-ai anymore, but try adding `setlocal buftype=''` after `setlocal filetype`. I did not test this...

**Comment by madox2** [comment]
The way presets and `scratch_buffer_keep_open` property work has slightly changed. So maybe these commits could be related to this issue:
https://github.com/madox2/vim-ai/commit/ff479a02e8c7fce544f51ffc4be2542e7dd88039#diff-c5343a5d13850471f849776609ce57fc060df53e28763bb19f8c407e81854970R59

**Comment by madox2** [comment]
Maybe you don't have to create a custom preset at all. Opening an `.aichat` file should be enough to start a chat. E.g. something like this:

```vim
let g:vim_ai_mod = {}
let g:vim_ai_mod['chat_files_path'] = '~/cloud/projects/chatgpt/chats-vim-ai/'

function! g:vim_ai_mod.CreatePersistentChat()
  let l:unique_id = system('uuidgen')
  let l:timestamp = strftime('%Y-%m-%d-%H-%M-%S')
  let l:filename = l:timestamp . '-' . printf('%.8s', l:unique_id) . '.aichat'
  execute 'e' g:vim_ai_mod['chat_files_path'] . l:filename
endfunction

command! AINewPersistentChat call g:vim_ai_mod.CreatePersistentChat()
```

**Comment by Konfekt** [comment]
>  I get an error about buftype=nofile

Short answer is 

https://github.com/madox2/vim-ai/blob/1d476136a0eb716171608290c8d189cdb79bcfa2/autoload/vim_ai.vim#L59

Not much to do about it other than fiddling with autocmd's as your custom function is called here

https://github.com/madox2/vim-ai/blob/1d476136a0eb716171608290c8d189cdb79bcfa2/autoload/vim_ai.vim#L45

before above line

**Comment by nathanbraun** [comment]
> Maybe you don't have to create a custom preset at all. Opening an .aichat file should be enough to start a chat.

Yes I ended up doing something like this, it's working now. Thanks!
