### ISSUE TITLE
Please consider adding x.ai and other API support.

### ISSUE THREAD

**Issue by ioctl-user** [madox2/vim-ai#131]
May you provide config stubs or adding some examples how to use x.ai, claude.ai and local llama.cpp server?

**Comment by ioctl-user** [comment]
For example, I run the following server command:

```
llama-server -m ./qwen2.5-coder-14b-instruct-q4_k_m.gguf --verbose-prompt
```

Have the following vimrc config:

```
let g:vim_ai_model = {
    \ 'name': 'llama',
    \ 'endpoint': 'http://localhost:8080/completion',
    \ 'headers': {
        \ 'Content-Type': 'application/json'
    \ },
    \ 'method': 'POST',
    \ 'body': '{"prompt": "%s", "max_tokens": 100, "temperature": 0.7}'
\ }
```

Also have tried a lot of another options, but vim with `:AI "` command seems tries access default OpenAI server.

**Comment by kabads** [comment]
+1

**Comment by madox2** [comment]
@ioctl-user you have completely misconfigured the plugin. There is no `vim_ai_model` config variable, neither any of `endpoint`, `headers`, `method`, ... options.

Please read and follow the existing [configuration](https://github.com/madox2/vim-ai?tab=readme-ov-file#configuration). You should be able to configure plugin with any OpenAI compatible API, see [instructions here](https://github.com/madox2/vim-ai?tab=readme-ov-file#using-custom-api)
