### ISSUE TITLE
How to provide more context to AI and AIEdit

### ISSUE THREAD

**Issue by MartyLake** [madox2/vim-ai#132]
Hello,
My goal is to provide context to the model when doing a call to `:AI` or `:AIEdit`.

My first try was to pass the whole file to `AIEdit`, but then I have to wait for the model to write the same file again and it takes time.

```
" custom command adding filetype to the instruction
function! AIEditSyntaxFn(...) range

  if a:firstline < a:lastline
    let l:firstline = a:firstline
    let l:lastline  = a:lastline
  else
    " Whole file
    let l:firstline = 0
    let l:lastline  = line('$')
  endif

  let l:instruction = "programming language is " . &filetype
  if a:0
    echomsg "a:1" . a:1
    let l:instruction = l:instruction . " - " . a:1
  endif
  exe l:firstline . ',' . l:lastline . 'call vim_ai#AIEditRun(g:vim_ai_edit, l:instruction)'
endfunction
command! -range -nargs=? AISEdit <line1>,<line2>call AIEditSyntaxFn(<f-args>)
```
I wish I could select the line I want the model to edit, and pass the whole buffer as context only. Even better, I wish I could pass all the open buffers as context.

I read the documentation that says that you can include files using the `>>>> include` syntax. However, I don’t understand where to input this.

Did you already try something similar ?
Best,

**Comment by madox2** [comment]
I just quickly prototyped, this custom command should send content of the file as a system message:

```vim
let g:initial_file_prompt_prefix =<< trim END
>>> system
You are a code assistant.
Answer shortly, consisely and only what you are asked.
Do not provide any explanantion or comments if not requested.
If you answer in a code, do not wrap it in markdown code block.
Below is the code context to the questions:
END

function! AIAskFileFn(...) range
  let l:instruction = a:0 > 0 ? a:1 : ""
  let l:selection = a:0 > 1 ? a:2 : 0
  let l:buf_nr = bufnr("%")
  let l:buf_content = join(getbufline(l:buf_nr, 1, '$'), "\n")
  let l:initial_prompt_prefix = join(g:initial_file_prompt_prefix, "\n")
  let l:initial_prompt = l:initial_prompt_prefix . "\n######\n" . l:buf_content . "\n######"
  let l:config = {
  \  "options": {
  \    "initial_prompt": l:initial_prompt,
  \  },
  \}
  exe a:firstline.",".a:lastline . "call vim_ai#AIEditRun(l:config, l:instruction, l:selection)"
endfunction
command! -range -nargs=? -complete=customlist,vim_ai#RoleCompletion AIAskFile <line1>,<line2>call AIAskFileFn(<q-args>)
```

It should be easy to extend it with multiple buffers or `>>> include` syntax.
Please let me know if this or similar command actually improved your AI workflow.

**Comment by MartyLake** [comment]
Injecting in the initial prompt is a much better idea! I tested real quick with `qwen2.5-coder` and it is behaving much like what I would expect.

I guess being able to pour all open buffers into `AIAskFile` would be fantastic: I could just query with `AIAskFile` and whenever I realize that some context is missing, I open that other file in another tab for example and run the same query again.

But what you just did is already very good I think.  I would need to continue using it in a real working situation for sometimes first.

**Comment by madox2** [comment]
You can also share files solely with an initial prompt, for example see this "codebase" role:

```ini
[codebase]
[codebase.options]
initial_prompt =
  >>> system
  You are a code assistant.
  Answer shortly, consisely and only what you are asked.
  Do not provide any explanantion or comments if not requested.
  If you answer in a code, do not wrap it in markdown code block.
  I will share sorce code that you use as a context to provide better answers.
  >>> include
  /home/user/myproject/requirements.txt
  /home/user/myproject/**/*.py
```

This will however send content of any matching file (not only open buffers).
Anyway, you probably want to make sure not to share any sensitive files, such as secrets.

**Comment by madox2** [comment]
Right, there was a breaking change, now you need to pass range as first parameter. See [custom commands](https://github.com/madox2/vim-ai?tab=readme-ov-file#custom-commands)

**Comment by MartyLake** [comment]
For posterity, the macro is:
```
let g:initial_file_prompt_prefix =<< trim END
>>> system
You are a code assistant.
Answer shortly, consisely and only what you are asked.
Do not provide any explanantion or comments if not requested.
If you answer in a code, do not wrap it in markdown code block.
Below is the code context to the questions:
END

function! AIAskFileFn(...) range
  let l:instruction = a:0 > 0 ? a:1 : ""
  let l:selection = a:0 > 1 ? a:2 : 0
  let l:buf_nr = bufnr("%")
  let l:buf_content = join(getbufline(l:buf_nr, 1, '$'), "\n")
  let l:initial_prompt_prefix = join(g:initial_file_prompt_prefix, "\n")
  let l:initial_prompt = l:initial_prompt_prefix . "\n######\n" . l:buf_content . "\n######"
  let l:config = {
  \  "options": {
  \    "initial_prompt": l:initial_prompt,
  \  },
  \}
  exe a:firstline.",".a:lastline . "call vim_ai#AIEditRun(l:selection, l:config, l:instruction)"
endfunction
command! -range -nargs=? -complete=customlist,vim_ai#RoleCompletion AIAskFile <line1>,<line2>call AIAskFileFn(<q-args>)
```
