### ISSUE TITLE
Allow single undo

### ISSUE THREAD

**Issue by Kamilcuk** [madox2/vim-ai#14]
To undo AIEdit I press `u` and wait and wait and wait and wait. Would be great if the stuff posted by AIEdit could be undone with one `u` click.

ai.vim uses "indicator" to do that https://github.com/aduros/ai.vim/blob/main/lua/_ai/commands.lua#L64

**Comment by Kamilcuk** [comment]
Hi, thanks for amazing plugin!

$ cat /etc/os-release 
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
...
$ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/x55yfs57l7bm6ms0584lhwiz7h1zxr7n-neovim-unwrapped-0.9.0/share/nvim
"

Run :checkhealth for more info

nvim installed with nix-env.

When I make a visual selection, then type `:AIEdit do stuff`, then AI fills the stuff, then I have to click multiple u to undo it.

**Comment by madox2** [comment]
I check on Fedora 37, NVIM v0.8.3 and NVIM v0.10.0-dev+64-g37bb40701 and it works as expected with a single undo.
It seems there is something else different on your environment that causes broken undo sequence.
Maybe a conflict with another plugin, could you try it again with all plugins but vim-ai disabled?
