### ISSUE TITLE
maybe a bug: after completion, the text "completing" still show in the status line

### ISSUE THREAD

**Issue by jackywu** [madox2/vim-ai#16]
like the screenshot：
![Xnip2023-04-14_06-30-15](https://user-images.githubusercontent.com/587955/231897114-7cce3304-b9a4-460e-b5a1-a500cfce852b.png)

**Comment by jackywu** [comment]
@madox2 
![Xnip2023-04-15_20-19-51](https://user-images.githubusercontent.com/587955/232223202-9995bfb4-2ced-4fae-933c-a6d6ddc5e2bc.png)
![Xnip2023-04-15_20-20-44](https://user-images.githubusercontent.com/587955/232223208-516e677f-53ae-46cc-bbc2-ffed9b73eb75.png)

**Comment by jumski** [comment]
same issue on my pc:

```shell
❯ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info


❯ uname -a
Linux jumski-manjaro-pc 5.15.108-1-MANJARO #1 SMP PREEMPT Thu Apr 20 11:41:14 UTC 2023 x86_64 GNU/Linux

❯ python --version
Python 3.8.16

❯ pip3 show pynvim
Name: pynvim
Version: 0.4.3
Summary: Python client to neovim
Home-page: http://github.com/neovim/pynvim
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /home/jumski/.asdf/installs/python/3.8.16/lib/python3.8/site-packages
Requires: greenlet, msgpack
Required-by:

```

**Comment by madox2** [comment]
Maybe it is caused by a specific vim configuration. To confirm this theory, could you please use just defaults, disable all plugins but vim-ai and let me know if it is still an issue?

**Comment by madox2** [comment]
Applied a fix that should resolve this issue, although I am still curious how to reproduce it. Please update the plugin and let me know if this fixed the issue in your environments.
