### ISSUE TITLE
Error installing on MacOS

### ISSUE THREAD

**Issue by adueck** [madox2/vim-ai#18]
Using MacOS Ventura 13.0.1 and following the [manual installation](https://github.com/madox2/vim-ai#manual-installation) instructions, I get the following error message:

```
Error detected while processing /Users/adam/.config/nvim/plugin/vim-ai/autoload/vim_ai.vim:
line    1:
E117: Unknown function: vim_ai_config#load
Press ENTER or type command to continue
```

**Comment by madox2** [comment]
Hi, thanks for reporting! I will have a look at it, but I it seems to be just a matter of installation instructions.
Unfortunately I am not able to test on MacOS, could you try to install with [vim-plug](https://github.com/junegunn/vim-plug) (or any other plugin manager) and let me know if it works?

**Comment by madox2** [comment]
I was able to reproduce it. The documentation for manual installation was incorrect. Please check out to the updated installation instructions.

**Comment by adueck** [comment]
Thanks that works great now. You've made an **awesome** plugin. 👏

**Comment by adueck** [comment]
Also works great inside VSCode with the [VSCode Neovim extension](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim) 👍
