### ISSUE TITLE
Trouble using the AIEdit command

### ISSUE THREAD

**Issue by tvvmongeek** [madox2/vim-ai#2]
Hello,

First, thanks for this awesome VIM plugin.

I have some trouble using the AIEdit command.
I am trying something similar as the demo gif in the readme, but it seems that the visual-selected text i am trying to ask openAI to manipulate is not sent.

Here are the steps i am doing : 

- Visual-selecting a list of items (shift + v)
- typing   :AIEdit make this data JSON
- pressing enter

The AI returns me what seems to be a "basic" json structure with some random example data.

I am doing something wrong when i try to use the AIEdit command ?

Best regards,

tvvmongeek

**Comment by madox2** [comment]
Hi, thank you for reporting the issue! I think I know what the problem is. I am getting visually selected text from `*` register, what seems to be supported only in vim with X11 support (`:h x11-selection`). I will look for a solution, but any help would be welcome

**Comment by madox2** [comment]
@tvvmongeek I think I have managed to fix this issue. Please let me know if it works for you

**Comment by plorry** [comment]
Nice! Had this same issue yesterday and saw this Issue thread. Updated plugin, re-ran :AIEdit commands, and got it working! Thanks for the quick fix!

**Comment by tvvmongeek** [comment]
Hi @madox2 !

You were right, i was using vim inside an ssh session to a remote machine at home.
I can confirm your fix works very well !

Thank you !

**Comment by cposture** [comment]
I've noticed that the code uses a:firstline and a:lastline to get the content selected by the user. However, this may include extra content when the user is in visual mode and does not exactly fulfil the requirement in some scenarios. 

Do you think it would be reasonable to change it to the content actually selected by the user? I am willing to contribute my code.
@madox2

**Comment by cposture** [comment]
@madox2 please review pr https://github.com/madox2/vim-ai/pull/64
