### ISSUE TITLE
how to install with lazy plugin manager?

### ISSUE THREAD

**Issue by edersohe** [madox2/vim-ai#21]
This is more of a question than an issue, how can I use this plugin with the lazy plugin manager in Neovim? I've tried manual installation but the plugin doesn't get picked up. Thanks in advance for your help.

**Comment by madox2** [comment]
Hi thanks for opening the issue! I am not very familiar with lazy.nvim but I tried this minimal config and all AI commands work as expected:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "madox2/vim-ai"
})
```

Could you provide me more details on "the plugin doesn't get picked up in manual installation"?

**Comment by edersohe** [comment]
after checking how python3 is supported by neovim and installing pynvim the problem went away

```
python3 -m pip install --user pynvim
```

I put the error here for future reference and I close the topic. Thanks @madox2 

```
2023-04-18T20:55:58 lazy.nvim  ERROR Failed to source `/home/edersohe/.local/share/nvim/lazy/vim-ai/plugin/vim-ai.vim`

vim/_editor.lua:341: /home/edersohe/Projects/mylinux/dotfiles/.config/nvim/init.lua..nvim_exec2() called at /home/edersohe/Projects/mylinux/dotfiles/.config/nvim/init.lua:0../home/edersohe/.l
ocal/share/nvim/lazy/vim-ai/plugin/vim-ai.vim, line 3: Vim(echoerr):Python 3 support is required for vim-ai plugin

# stacktrace:
  - vim/_editor.lua:341 _in_ **cmd**
  - Projects/mylinux/dotfiles/.config/nvim/init.lua:189
```
