### ISSUE TITLE
gpt-4 model is not working

### ISSUE THREAD

**Issue by nekowasabi** [madox2/vim-ai#26]
I tried GPT-4 model by vim-ai.
However, the following error occurred
The message says that the GPT-4 model is not supported.

![gvim_9lKFmUpVtU](https://user-images.githubusercontent.com/3657473/235024444-b41fee49-cd73-4846-abff-824105b1d639.png)

How can I configure it to use the gpt-4 api?

### setting
OS:  windows11
Vim: Gvim 9.0 1-1221

```
let g:vim_ai_edit = {
			\  "options": {
			\    "model": "gpt-4",
			\    "max_tokens": 1000,
			\    "temperature": 0.1,
			\    "request_timeout": 10,
			\  },
			\}
```

**Comment by madox2** [comment]
Hi, `gpt-4` is a chat model therefore you need to configure edit/complete for a chat engine:
https://github.com/madox2/vim-ai#using-chat-engine-for-completion-and-edits

Something like this should work:

```vim
let g:vim_ai_edit = {
\  "engine": "chat",
\  "options": {
\    "model": "gpt-4",
\    "max_tokens": 1000,
\    "temperature": 0.1,
\    "request_timeout": 20,
\    "selection_boundary": "",
\    "initial_prompt": "",
\  },
\}
```

I would also recommend to set an initial prompt, see more explanation in README.

**Comment by nekowasabi** [comment]
It worked.
Thank you!!
