### ISSUE TITLE
Feature inquiry/request: Setting max linewidth for AI output

### ISSUE THREAD

**Issue by aJns** [madox2/vim-ai#27]
Hello,

I usually use vim on a side monitor or split, so that I can comfortably read maybe 130 characters. AI output usually exceeds this.

Is there a way to set a maximum linewidth? How difficult would it be to add an option? I could look into implementing that option with some guidance.

Best regards,
aJns

**Comment by madox2** [comment]
Hi, I assume your vim/nvim is configured to not wrap lines. If that's the case, a good solution could be wrapping lines just in the chat, e.g. run this within a chat window: `:setlocal wrap`.

Does it help?

**Comment by aJns** [comment]
`:setlocal wrap` does not seem to have any effect with `AIChat` or `AI`. I ran both in an empty buffer.

**Comment by madox2** [comment]
I am not sure what are you trying to accomplish. Could you attach a screenshot what is the actual behavior and what would you like it to be?

**Comment by madox2** [comment]
I have added a new `ui.paste_mode` option that allows indentation when disabled. This would also allow you to set `textwidth` for the chat buffer which breaks lines automatically. For example you can use it like this:

```vim
let g:vim_ai_chat = {
\  "ui": {
\    "paste_mode": 0,
\  },
\}
autocmd FileType aichat setlocal textwidth=130
```

Note that it is experimental as it could mess up indentation completely if used in incorrect context, but should be safe for use in the chat buffer.

**Comment by aJns** [comment]
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/9674780/235888157-8766ca6f-831e-4c22-a5ea-43dafcd7feeb.png)

**Comment by jeromedalbert** [comment]
`setlocal textwidth` works for me with `paste_mode` set to 0.

I think AIChat should be configured with a textwidth by default.

**Comment by madox2** [comment]
I think that it depends. If you use to copy data from the chat, it could be quite uncomfortable to join lines every time. Also it does not fit well when used in combination with right sider (`"open_chat_command": "preset_right"`). For now I will keep defaults as they are, add this tip on the wiki page.

**Comment by marcelarie** [comment]
I add it to the initial prompt:
```lua
		vim.cmd [[
			let g:vim_ai_chat = {
			\  "options": {
			\    "model": "gpt-4-1106-preview",
			\    "max_tokens": 1000,
			\    "temperature": 1,
			\    "request_timeout": 20,
			\    "selection_boundary": "",
			\    "initial_prompt": ">>> system\n - You are a code assistant\n - Always add line breaks at collumn 78\n - Always use 80 characters for each line of the respone\n - If you attach a code block add syntax type after ``` to enable syntax highlighting.\n",
			\  },
			\  "ui": {
			\    "code_syntax_enabled": 1,
			\    "populate_options": 0,
			\    "open_chat_command": "preset_right",
			\    "scratch_buffer_keep_open": 0,
			\  },
			\}
		]]

```

**Comment by brunobispo** [comment]
Does anybody know if it is possible to set `set wrap` for all chats without having to manually run it every time I start a new one?
