### ISSUE TITLE
aichat files storage / history / backup

### ISSUE THREAD

**Issue by jumski** [madox2/vim-ai#28]
First of all - I love your plugin, it was the cherry on top of the OpenAI cake. I installed it today and i think i have used it hundred of times already - impossible to go back to copy pasting stuff now.

I immediately think about storing all my chats and saving selected chats, but i find writing full paths or saving in current dir kind of cumbersome.

Do you have any ideas or some established workflow or best practices on where to save .aichat files? How do you do it?
Maybe you have some ideas? Would love to try to hack something up to make this plugin even better.

Cheers!

**Comment by madox2** [comment]
Thank you for the nice feedback!

First thing that comes to mind is to store aichat files somewhere relative to your home directory. E.g. save chat like this `:w ~/chat/mychat.aichat` and then open the directory to list/open chats `:e ~/chat`

If it still feels cumbersome, you could create a custom function/command pointing to any directory you need.

Hope this helps

**Comment by jumski** [comment]
thanks for feedback!

after few days with vim-ai i feel like this issue is not relevant anymore - it is too easy to start new chat that my need to store everything is gone, I'll just manually save what i will consider worth saving

cheers!

**Comment by madox2** [comment]
Thanks for the feedback guys! To be honest I am quite reluctant to add history feature to the chat because there is just so many ways how to do it. It feels like keeping it plain .aichat files would allow anybody use it their own way, integrate with other plugins like mentioned above (telescope, ranger, fzf, etc.).

Anyway if you put together anything useful please don't hesitate to share it on the [Wiki](https://github.com/madox2/vim-ai/wiki).

**Comment by BonaBeavis** [comment]
With this pull [request](https://github.com/madox2/vim-ai/pulls), I have a cleaner solution:
```vim
let g:vim_ai_mod = {}
let g:vim_ai_mod['chat_files_path'] = '~/cloud/projects/chatgpt/chats-vim-ai/'
let g:vim_ai_open_chat_presets = {
\  'preset_below': 'below new | call vim_ai#MakeScratchWindow()',
\  'preset_tab': 'tabnew | call vim_ai#MakeScratchWindow()',
\  'preset_right': 'rightbelow 55vnew | setlocal noequalalways | setlocal winfixwidth | call vim_ai#MakeScratchWindow()',
\  'preset_persistent': 'call g:vim_ai_mod.CreatePersistentChat()'
\}

function! g:vim_ai_mod.CreatePersistentChat()
  let l:unique_id = system('uuidgen')
  let l:timestamp = strftime('%Y-%m-%d-%H-%M-%S')
  let l:filename = l:timestamp . '-' . printf('%.8s', l:unique_id) . '.aichat'
  execute 'e' g:vim_ai_mod['chat_files_path'] . l:filename
  setlocal filetype=aichat
endfunction
command! AINewPersistentChat call vim_ai#AINewChatRun('persistent')

```

**Comment by thiswillbeyourgithub** [comment]
I too think history is a must, I don't use ChatGPT only for coding but also for lots of general information and it gets annoying when you have to explain some things all over again to get the info you need :) I'm not thinking anything fancy btw, even just a rotating log file would be fine to me.

I'm very interested in @BonaBeavis  solution.

**Comment by jumski** [comment]
I have solved it for me with a handy **aichat** fish function that i call from shell and also as a tmux popup

it will ask for a prompt if called without arguments and will use this prompt and mktemp to create a slugified unique .aichat file

see it here:

https://github.com/jumski/dotfiles/blob/468ff63a3680ec7f354f2d68a5e06b0f846f41c9/fish/functions/aichat.fish#L1-L21

(requires this fn https://github.com/jumski/dotfiles/blob/468ff63a3680ec7f354f2d68a5e06b0f846f41c9/fish/functions/slugify.fish#L1-L17)

**Comment by prettymuchbryce** [comment]
History would be a great feature. I'm imagining something similar to the ChatGPT UI, where the history lives in a panel on the left-hand side in chronological order.

My biggest issue is that I often end up accidentally closing my `vim-ai` splits, or I want to go back and reference a previous query. It's unfortunate that this is not really possible, and I notice I am still reaching for the ChatGPT web interface at times for this reason. My goal would be to be able to never leave vim.

I'd like to see this implemented (perhaps as an optional feature) in `vim-ai`, but understand if the maintainer feels it is out of scope. I believe storing all history in a single directory is acceptable, and of course allow the directory location to be chosen through configuration.
