### ISSUE TITLE
:AIEdit leads to a python error

### ISSUE THREAD

**Issue by Loungagna** [madox2/vim-ai#29]
After updating to the latest release of vim-ai in nevoid on my Mac, here is what an :AIEdit prompt generates:

lazy/vim-ai/py/complete.py", line 6, in <module>
    engine = config['engine']
             ~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Python is 3.11.3, Neovim is latest stable

**Comment by madox2** [comment]
Hi, thanks for reporting the issue! This looks weird because `config` variable is supposed to be a dictionary, not a string.

Is it just `AIEdit` or the same happens in `:AI` and `:AIChat`?
By any chance, didn't you misconfigure `g:vim_ai_edit` in some way?
