### ISSUE TITLE
No request_timeout in the OpenAI API

### ISSUE THREAD

**Issue by axeltib** [madox2/vim-ai#3]
Hello!

First off: very nice package you have here! I wanted to start using it but instantly ran into some issues with the request_timeout option. Referring to the API reference for OpenAI, there seem to not be any such option ([API for requests found here](https://platform.openai.com/docs/api-reference/completions/create)).  Just curious: why is it in here?

I have solved it by removing the option, and it now works for me. Is it possible for me to contribute with the changes in any way?

**Comment by dsummersl** [comment]
I ran into this problem too - and it was b/c I had version 0.20 -- might would be good to update your install.sh script to install the minimum version required by this plugin (something like `pip install "openai>=0.27"`

**Comment by madox2** [comment]
That is a great idea, thanks! I will update the script

**Comment by axeltib** [comment]
Perfect, I got it to work now. Thank you!

I had to upgrade what python version vim was running, and this could only be done by building vim from source. 

All in all, got it to work. Thank you for the help!
