### ISSUE TITLE
Levergage neovim and treesitter support

### ISSUE THREAD

**Issue by BonaBeavis** [madox2/vim-ai#31]
I have one example in mind: Explain a line of code.

This is the buffer in neovim:
```lua
local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0
        and vim.api
                .nvim_buf_get_lines(0, line - 1, line, true)[1] -- Cursor is on this line
                :sub(col, col)
                :match '%s'
            == nil
end
```

Now treesitter has [textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) for functions and objects. So it would be possible to create a command which takes the cursors line and the surrounding function/class to construct a prompt like this:

---

Explain this line:

```lua
.nvim_buf_get_lines(0, line - 1, line, true)[1]
```

In this function:

```lua
local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0
        and vim.api
                .nvim_buf_get_lines(0, line - 1, line, true)[1]
                :sub(col, col)
                :match '%s'
            == nil
end
```
---

The result could be shown in a floating window.

I will try to implement this, but before I wanted to ask if this is a good Idea, because this plugin is vimscript based and maybe I should try to do it with this plugin: https://github.com/dpayne/CodeGPT.nvim

I really would like to go with your plugin, because the AIChat buffer is a absolute killerfeature.

**Comment by madox2** [comment]
It is definitely an interesting idea! I can see 2 things here:
1. constructing prompt like you suggested
2. displaying result in a floating window

For the first one I think you could take a look at [custom commands](https://github.com/madox2/vim-ai/wiki/Custom-commands). This is also the place where I would like to keep all specialized functions/commands for now.

Regarding the floating window, that would be a great improvement to the plugin core. I can imagine a new config option telling how/where to render the response. Maybe it would be even possible to stream it and populate floating window asynchronously.

**Comment by BonaBeavis** [comment]
Ok have a quick and dirty implementation for explaining a line:

```vimscript
function! g:vim_ai_mod.AIChatExplainLine()
  let l:current_line = getline('.')
  call setreg('"', '')
  execute 'normal! :TSTextobjectSelect @block.outer'
  execute 'normal! y'
  let l:context = getreg('"')
  if empty(l:context)
    execute 'normal! -5kV10jy'
    let l:context = getreg('"')
  endif
  let l:prompt = "Explain this line:\n```" . &filetype . "\n" . l:current_line . "\n\n```\nHere is the context:\n```" . &filetype  . "\n" . l:context . "\n```"
  call vim_ai#AIChatRun(v:false, {}, l:prompt)
endfunction
command! AIChatExplainLine call g:vim_ai_mod.AIChatExplainLine()
```

**Comment by madox2** [comment]
Closing, please share useful custom commands like this on the [Wiki](https://github.com/madox2/vim-ai/wiki/Custom-commands)
