### ISSUE TITLE
[Feature Request] Redo

### ISSUE THREAD

**Issue by jinpeng-s** [madox2/vim-ai#4]
Dear Developer,

I wanted to start by expressing my appreciation for your exceptional work on the plugin. As a user, it has been tremendously helpful for my text processing work.

Specifically, I have been using the `:AIEdit` function in visualization mode to optimize sentence expressions. However, there have been instances when I was not satisfied with the result and had to use the `u` key to undo the operation and repeat it. This process can become tiresome if we have to repeat it multiple times. Therefore, I believe that adding a redo feature to the plugin would significantly simplify the users' operation and save time.

Finally, I want to commend you on creating such a remarkable plugin. It has made a significant impact in my workflow, and I am grateful for your dedication and hard work.

Thank you again for all your efforts.

Best regards.

**Comment by madox2** [comment]
Hi, thank you for kind words! I am considering to add such feature but I am still trying to figure out what would be the best way. In the meantime what could help is to undo last change `u`, go to visual selection `gv` and then repeat the command either by `:AIEdit ...` or `@:`.

You might also find useful to setup a key binding for this, for example:
```vim
" redo AI commands started from visual selection
nnoremap <leader>r ugv@:<CR>

" redo AI commands without selection and chat answers
nnoremap <leader>t u@:<CR>
```

**Comment by jinpeng-s** [comment]
Thank you for your advice! It was very helpful to me.

**Comment by madox2** [comment]
Hi again, check out the new [`:AIRedo`](https://github.com/madox2/vim-ai#airedo) command.

**Comment by jinpeng-s** [comment]
Great job! Thank you for implementing this amazing feature in a smooth and seamless way. You've made my productivity in Vim even better :)
