### ISSUE TITLE
Make `max_tokens` optional

### ISSUE THREAD

**Issue by BonaBeavis** [madox2/vim-ai#42]
The behavior of the [`max_tokens`](https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens) is not very intuitive.

It will break in the following scenario:

gpt4 token limit ~= 8000
max_tokens = 6000
prompt = 3000

This will gives a 400 http error, my gues is that they add prompt and max_tokens beforehand and compare it against the token limit. So it behaves more like min_token while validating the request.

Solution is not to set the `max_tokens` parameter in the api request.

**Comment by madox2** [comment]
Hi, that looks strange. I am getting 400 error only when I set max tokens above the limit (unfortunately I can try only in gpt-3). Could set `let g:vim_ai_debug = 1` reproduce the issue and share the log from `/tmp/vim_ai_debug.log`?

**Comment by madox2** [comment]
To exclude `max_tokens` from the request you can now set it to `0`
