### ISSUE TITLE
[Bug Report] Empty reply when using :AIChat

### ISSUE THREAD

**Issue by jinpeng-s** [madox2/vim-ai#5]
When using `:AIChat`, there may be cases that GPT provides empty answers:

![CleanShot 2023-03-27 at 11 03 22](https://user-images.githubusercontent.com/88496834/227830687-5ec6aa6e-ff59-41aa-a927-a3defa57cad1.png)

I would be happy to help, please let me know what information you need. Perhaps a debug module would allow me to help you better.

**Comment by madox2** [comment]
Hi, thank you for reporting the issue!
- Do you have any clues that suggest this is a bug in `vim-ai` plugin?
- How often does it return empty messages for you? what type of prompts?
- What vim/openai-python/OS versions are you using?

**Comment by s5unty** [comment]
`vim`: 8.2.3995-1ubuntu2.1
`vim-ai`: git-b5c8ebc
`python`: 3.10.6
`openai-python`: 0.27.2
`os`: Ubuntu 22.04
`prompts`: 
1. 第一届世界杯的举办地
2. 第二届世界杯的举办地
3. 第三届世界杯的举办地

| ![image](https://user-images.githubusercontent.com/50655/229327344-91c87afa-ef39-48de-8e5f-565a4872301b.png) | ![image](https://user-images.githubusercontent.com/50655/229327559-86db5e5c-c532-423f-9034-9e47a9e6ffa9.png) |
| --- | --- |

Using prompts in English, no issues encountered
![image](https://user-images.githubusercontent.com/50655/229327449-8358e293-6b7f-4d6f-b9ec-42590d8db698.png)

**Comment by madox2** [comment]
Hey guys, thank you for the cooperation! I think I have worked it out. It has something to do with newlines in the beginning or at the end of the prompt, in that case openai occasionally returns an empty message. Please update the plugin and let me know if the issue occurs again
