### ISSUE TITLE
Hello! + feature request: Azure Openai API integration + notes

### ISSUE THREAD

**Issue by solyarisoftware** [madox2/vim-ai#51]
Hi Martin,

First of all, thank you for sharing your project! 
I recently came across vim-ai while contemplating how to implement my idea of automating the interaction with a large language model (LLM) web playground, similar to the openai web playground. 
In line with this concept, I posted a thought-provoking question on this link: https://vi.stackexchange.com/questions/42827/exploring-the-potential-of-vim-editor-as-an-efficient-multi-prompt-playground-fo

Before delving into my perspective and the potential integration with your project, I would like to submit a minor yet crucial feature request: enabling integration with the Microsoft Azure OpenAI service, as an alternative API endpoint.

As you might be aware, the OpenAI APIs are now accessible on the Microsoft Azure platform. However, as is often the case with Microsoft, they tend to introduce complexity into the process... The API interface differs slightly in this context. Here are two links that highlight the distinctions:
- https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints
- https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions

Essentially, Microsoft requires the following setup:
```bash
export OPENAI_API_KEY=<AZUREKEY>
export OPENAI_API_BASE="https://<AZUREPROJECTNAME>.openai.azure.com/openai/deployments/text-davinci-003/completions?api-version=2022-12-01"
```

BTW, The API_BASE in Azure parlance is also called the endpoint.

All in all, to run the Azure APIs (instead of the Openai APIs) you need to call the specific endpoint specified in the OPENAI_API_BASE var. Maybe found the line involved: https://github.com/madox2/vim-ai/blob/main/py/chat.py#L72

```python
        response = openai_request('https://api.openai.com/v1/chat/completions', request, http_options)
```
A possible solution is to avoid to hardcode the URL to  'https://api.openai.com/v1/chat/completions', instead getting it from the environment variable  OPENAI_API_BASE?

Beside the above point, I'm looking forward to discussing my perspective and the potential integration further.

Best regards,
giorgio

**Comment by madox2** [comment]
Hi, that's a great idea! Then it would be also possible to run it with any openai-compatible api, for example using https://github.com/lm-sys/FastChat

I would prefer to keep configuration in .vimrc, it could be something like:

```vim
let g:vim_ai_chat['options']['api_url'] = 'https://...'
```

Btw. the reason why OPEN_API_KEY is configured via environment and not in .vimrc is that .vimrc is not a good place to keep sensitive information as many people share their config.

**Comment by solyarisoftware** [comment]
Thanks for the feedback!

>  Then it would be also possible to run it with any openai-compatible api,

Yes, even though this introduces another point of improvement: you used the OpenAI REST interface, which is great, but I might suggest using the Python OpenAI completion API directly. These are updated wrappers of the HTTP services. This allows for faster implementation of completions with multiple LLM APIs as a class. Maybe

> I would prefer to keep configuration in .vimrc

Yes,I suggested using the OS environment as an alternative, as you yourself suggested here: https://github.com/madox2/vim-ai#prerequisites. But well, it's debatable.

**Comment by madox2** [comment]
Earlier version of this plugin used python package (openai-python) but has been re-implemented to plain http (urllib). That's because external python packages may be difficult to install for vim/neovim across different environments (linux, windows, ...), one may need to compile vim from source, and there were even more issues with it

**Comment by solyarisoftware** [comment]
Weird, but I absolutely believe you!

**Comment by madox2** [comment]
Should be possible now with Azure, see https://github.com/madox2/vim-ai#using-custom-api
