### ISSUE TITLE
open vim error with "Python 3 support is required for vim-ai plugin"

### ISSUE THREAD

**Issue by plusStar** [madox2/vim-ai#52]
I had install python3, but when I start vim in termail, there is error:
Error detected while processing .vim/pack/plugins/start/vim-ai/plugin/vim-ai.vim:
line    3:
Python 3 support is required for vim-ai plugin

**Comment by plusStar** [comment]
> hi your vim version probably doesn't support python3 mode, check it with command
> 
> ```shell
> vim --version | grep "+python3"
> ```
> 
> If you get "-python3", you need to install a vim version that enable python 3 integration (it depends on your OS, GUI environment, etc).
> 
> BTW, of course you need python3 installed on your host

I use brew install vim which is python3 support, but it is still with that error.
GPT tell me that the default vim command might still point to the system's built-in Vim (usually with Python 2 support). To use the newly installed Vim with Python 3 support, you can set up an alias in your terminal to point the vim command to the new Vim.
Then the problem is solved.😂

**Comment by jamilraichouni** [comment]
> > You need to have the package pynvim installed. So in vim:
> > :!pip3 install pynvim
> 
> Are you sure this works on standard vim?

Sorry, this was Neovim specific.

In Neovim you can set
`let g:python3_host_prog = "/path/to/your/favorite/python"`
in your config.

IMHO: Whatever python is used (in your PATH), it needs the pip package `pynvim` installed.
