### ISSUE TITLE
Bold Text Formatting.

### ISSUE THREAD

**Issue by jediaxe** [madox2/vim-ai#53]
First off, big fan of your Vim plugin here. It's been a game changer for me.

I've been using it for a while now and noticed something. When the AI uses double asterisks to mark text as bold (markdown style), the plugin doesn't actually show the text in bold. 

For instance, if the AI spits out a list like:

- **Item 1**
- **Item 2**
- **Item 3**

The items don't pop out in bold in Vim. they just show the double asterisks instead. - ** Item 1 **

It'd be super cool if the plugin could support bold text formatting when double asterisks are used (and double underscores __ text __ in case AI decides to use them instead, and maybe italic with single * text * and _ text _ too?). I think it'd make the AI's output easier to read, especially for titles and lists.

I get that this might not be a quick fix, but I wanted to throw the idea out there. Thanks for considering it, and keep up the awesome work on the plugin!

Edit: A workaround is to create a file in ~/.vim/syntax/aichat.vim and populate it with the follwoing:
```
syntax region markdownItalic matchgroup=ItalicDelimiter start="\*" end="\*" concealends
highlight ItalicDelimiter cterm=italic gui=italic
highlight markdownItalic cterm=italic gui=italic

syntax region markdownBold matchgroup=BoldDelimiter start="\*\*" end="\*\*" concealends
highlight BoldDelimiter cterm=bold gui=bold
highlight markdownBold cterm=bold gui=bold
```
make sure to have ```set conceallevel=2``` in your .vimrc

**Comment by solyarisoftware** [comment]
Hi
yes you can give specific command as you proposed. 
More in general, if your LLM output is formatted with markdown markups as it seems from your example, in vim you can just say:

`:set syntax=markdown`

the true visualization depends on how markdown is managed in vim.
Probably you want to use some markdown plugin to enhance visualization.

**Comment by solyarisoftware** [comment]
BTW, if you want LLM completions in markdown format, just instruct the LLM to produce a completion in markdown (or any other text-based format, JSON, CSV, YAML, etc.). 

Your vim editor will manage the corresponding visualization enhancements setting/forcing a corresponding syntax with or without a specific plugin.

Also, in case of markdown maybe an idea is to build your prompt in markdown and you probably will have a completion in markdown ;-).

I propose to close the issue.
