### ISSUE TITLE
How to continue the `<SELECTION> :AIChat` using `.aichat` file?

### ISSUE THREAD

**Issue by zcysxy** [madox2/vim-ai#57]
Thanks for this amazing plugin! With the `.aichat` file, I can easily continue my chat conversation. However, when I select some text in another file and execute `:'<,'>AIChat`, a new chat session is opened. Is there a way to make it continue in the opened `.aichat` file?

**Comment by madox2** [comment]
Hi, it is possible to reuse open chat within the active window, e.g. if you open chat in a split (`AINew right`).
However it does not work for `.aichat` files, but it was part of the plan, this is related TODO comment:
https://github.com/madox2/vim-ai/blob/main/autoload/vim_ai.vim#L153

**Comment by zcysxy** [comment]
Thanks! The TODO comment is exactly what I wished for!

**Comment by madox2** [comment]
This feature has been added in #88
