### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by christian43** [madox2/vim-ai#61]
Hi there, 

since a few day the package did not work any more and displays the following error message. What is the issue? Any ideas how to fix it? Would be great!

`Fehler beim Ausführen von "function vim_ai#AIRun[19]..function vim_ai#AIRun":
Zeile   19:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/x/.vim/pack/vendor/start/vim-ai/py/complete.py", line 3, in <module>
    vim.command(f"py3file {plugin_root}/py/utils.py")
vim.error: Vim(py3file):vim.error: Vim:/Users/x/.vim/pack/vendor/start/vim-ai/py/utils.py:170: SyntaxWarning: invalid escape sequence '\<'`

**Comment by madox2** [comment]
Hi, I don't see any related changes lately that should cause this error. However the line `/Users/x/.vim/pack/vendor/start/vim-ai/py/utils.py:170` is pointing to a function which is used while error handling. So I think that maybe there was an original error swallowed by the error in the error handler. Could you share your vim/nvim version, os version and vim-ai configuration?

**Comment by christian43** [comment]
Hi, thank you very much for your fast response. 
<img width="1440" alt="Bildschirmfoto 2023-10-30 um 21 50 38" src="https://github.com/madox2/vim-ai/assets/5613876/a2a66d2a-b080-4685-9396-2b575a75b415">
<img width="250" alt="Bildschirmfoto 2023-10-30 um 21 56 24" src="https://github.com/madox2/vim-ai/assets/5613876/4dca3bbf-ea85-441e-9203-71040d034c6c">

I set up only an OPENAI-API-KEY.

**Comment by madox2** [comment]
My guess is that it has something to do with Python 3.12. I will look into it later

**Comment by madox2** [comment]
I think I managed to fix this, please update the plugin and let me know if it works.

**Comment by christian43** [comment]
without errors. Thanks for this great package!
