### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by JiehuiSun** [madox2/vim-ai#67]
I am a beginner, input `AIChat` return what the situation is?

**Comment by madox2** [comment]
Hi, I am not sure I understand what are you asking. Could you expand on your issue/question?

**Comment by JiehuiSun** [comment]
您好，邮件已收到。

**Comment by JiehuiSun** [comment]
> Hi, I am not sure I understand what are you asking. Could you expand on your issue/question?嗨，我不确定我是否明白你在问什么。你能详细谈谈你的问题/问题吗？

I'm really sorry, I forgot to paste the screenshot.

![chatai_return](https://github.com/madox2/vim-ai/assets/32083752/fdf3bf1a-e3cf-4323-8f0f-d31142b94a36)

**Comment by madox2** [comment]
@JiehuiSun if you want to use your code in the prompt, first you need to select it and then run `AIChat` command. It works the similar way like the  `AIEdit` in the [demo video](https://github.com/madox2/vim-ai/blob/main/demo.gif).

**Comment by JiehuiSun** [comment]
> @JiehuiSun if you want to use your code in the prompt, first you need to select it and then run `AIChat` command. It works the similar way like the `AIEdit` in the [demo video](https://github.com/madox2/vim-ai/blob/main/demo.gif).如果要在提示符中使用代码，首先需要选择它，然后运行 `AIChat` 命令。它的工作方式与演示视频中的工作 `AIEdit` 方式类似。
> 
> The `AIChat` command is also documented [here](https://github.com/madox2/vim-ai#aichat). You can also use vim help `:help vim-ai`此处还记录了该 `AIChat` 命令。你也可以使用 vim help `:help vim-ai`

Due to certain reasons, there are some issues with API key. I believe this issue is caused by API key, but the prompt is not clear and I mistakenly thought it was a plugin issue. Thank you for your patient answer. thanks
