### ISSUE TITLE
Include Code Files Before AI Prompt.

### ISSUE THREAD

**Issue by jediaxe** [madox2/vim-ai#69]
I find myself copy pasting a lot of code and sometimes in different languages into the chat prompt for AI generated ideas and solutions.

It'll be very handy if I could #include <files> before the chat prompt, so that these files are read by AI allowing it to reply accordingly. similar to the browser version where you can upload a file or multiple files and ask AI to review it or to generate documentation etc.

**Comment by madox2** [comment]
Sounds like a great idea. Maybe it could be a special keyword that would concatenate content of files to the user message. Something like this:

```
>>> user

Generate documentation for the following files:

>>> include

/home/user/myproject/requirements.txt
/home/user/myproject/**/*.py
```
