### ISSUE TITLE
What not using the edition end point?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [madox2/vim-ai#7]
I noticed that the completion is using text davinci whereas the edition endpoints have up to 8k context length and seem way more appropriate. I was curious as to why :)

**Comment by madox2** [comment]
You are probably right, edit endpoint looks more appropriate for editing text. However at the time I was experimenting with it, complete worked better for me, can't remember why was that.

Anyways I am still trying to figure out optimal defaults. I am also working on an improvement that allows more flexible configuration, tweaking endpoints and parameters. I will have it done soon, I will let you know

**Comment by madox2** [comment]
Edit endpoint currently does not support response streaming, which is something I'd like to have as it provides fast feedback to the user. Completion endpoint seems to be similarly powerful, can be used with up to 4k tokens (I assume that's a fair amount for the edition tasks). So honestly I don't see much benefit of using "edit" over "complete" now.

**Comment by thiswillbeyourgithub** [comment]
I strongly disagree and think vim-ai should support both, respectfully :).

Completion is incredible for a number of things (even *most* things) but the workflow of having to copy and paste things can be a hassle.

In my case, I tend to ask ChatGPT to do code for me, then copy the code to my current script, tweak it a bit. But then If I want more help from AI I have to give it again the whole new code whereas it would be simpler for me to just use frequently the edit end point.

I think that in many case the edition can be more suited than completion. For example when I asked ChatGPT or even davinci to translate some python strings for me it often scraped the formatting (the '''' on either side for example).

I think some workflows are better suited for edition than completion and would be delighted if vim-ai offered this choice :)
