### ISSUE TITLE
[request] setting to switch model/api

### ISSUE THREAD

**Issue by dkuku** [madox2/vim-ai#71]
With all that's going on in the ai space it would be useful to have a way to quickly switch models, prompts
`AIList` - list possible configs
`AISet` Mixtral-api
`AISet` Llama-local

**Comment by madox2** [comment]
I like the idea of supporting multiple configurations and switching between them. Maybe also some pre-defined configs would make sense. 

Currently vim-ai supports just one configuration at a time, but you can modify it while runtime. So a function that changes the configuration could work for you for now. Something like this:

```
function! AISetToLocalFn()
  let g:vim_ai_chat['options']['endpoint_url'] = 'http://localhost:8000/v1/chat/completions'
  let g:vim_ai_chat['options']['enable_auth'] = 0
endfunction

function! AISetToOpenAIFn()
  let g:vim_ai_chat['options']['endpoint_url'] = 'https://api.openai.com/v1/chat/completions'
  let g:vim_ai_chat['options']['enable_auth'] = 1
endfunction

command! AISetToLocal call AISetToLocalFn()
command! AISetToOpenAI call AISetToOpenAIFn()
```

**Comment by dkuku** [comment]
Thanks @madox2 for the reply. Did you consider using [LiteLLM](https://github.com/BerriAI/litellm) for communicating with openai? LiteLLM would give vim_ai access to around twenty providers - you only need to change the model name in settings.

**Comment by Koeng101** [comment]
I'd give a +1 for this being an actual function that is built in. This is one of the first things I thought of while trying out this package, which is how I found this feature. That makes at least two people. @madox2 I'd love to see your code snippet of "AISetToLocalFn" in the top level readme, it makes sense!

Awesome package, btw

**Comment by madox2** [comment]
Now it should be possible to define [a role](https://github.com/madox2/vim-ai?#roles) with a custom configuration, for example:

```ini
[local]
[local.options-chat]
endpoint_url = http://localhost:8000/v1/chat/completions
enable_auth = 0
```

and then use it: `:AIChat /local my prompt`
