### ISSUE TITLE
Improved GitCommitMessage Custom Command for Standardized Commit Messages

### ISSUE THREAD

**Issue by bardusco** [madox2/vim-ai#73]
I have created a improved version of the custom command GitCommitMessage that is designed to standardize commit messages, making it easier to automate the generation of release notes.

**Implementation:**
The command prompts the user to enter the intention of their commit and then generates a commit message based on the Conventional Commits format. This format includes a commit type (e.g., 'feat', 'fix', 'refactor'), an optional scope in parentheses, and a brief description that reflects the user's intention.

**Usage:**
To use this custom command, users can simply run `:GitCommitMessage` in their Vim editor after staging their changes with Git. The command will prompt them to enter the intention of the commit and generate a commit message accordingly.

**Benefits:**
This new custom command aims to provide more professional and standardized commit messages, which will be helpful for maintaining a well-structured Git history and facilitating the automatic generation of release notes.

**Full Code**
Here is the custom command:

```lua
-- Function to ask the user for the commit intention
local function askCommitIntention()
  return vim.fn.input('Enter the intention of the commit: ')
end

-- Function to obtain the git diff
local function getGitDiff()
  return vim.fn.system('git --no-pager diff --staged')
end

-- Function to build the prompt for the GPT-4 model
local function buildPrompt(diff, intention)
  local instructions = "Generate a professional git commit message using the" ..
      " Conventional Commits format. " ..
      "This includes using a commit type (such as 'feat', 'fix', 'refactor', etc.), " ..
      "optionally a scope in parentheses, and a brief description that reflects" ..
      " the intention '" .. intention .. "'." ..
      "- All explanation must be inside the commit message. Do not write" ..
      " anything before or affter." ..
      "- Do not enclose the commit message between ``` and ```" ..
      "- Add line breaks at collumn 78" ..
      "- Base the commit message on the changes provided below:\n" ..
      diff

  return instructions
end


-- Function to execute the AI and generate the commit message
local function generateCommitMessage()
  local intention = askCommitIntention()
  local diff = getGitDiff()

  if diff == "" then
    print("No changes detected. Cannot generate a commit message.")
    return
  end

  local prompt = buildPrompt(diff, intention)
  local range = 0
  local config = {
    engine = "chat",
    options = {
      model = "gpt-4-1106-preview",
      endpoint_url = "https://api.openai.com/v1/chat/completions",
      max_tokens = 1000,
      initial_prompt = ">>> system\nyou are a code assistant",
      temperature = 1,
    },
  }

  -- Execute the AI with the provided configuration
  vim.api.nvim_call_function('vim_ai#AIRun', { range, config, prompt })
end

-- Custom command to suggest a commit message
vim.api.nvim_create_user_command('GitCommitMessage', generateCommitMessage, {})

```

**Commit Example:**
I have provided an example commit message generated by the improved GitCommitMessage command:

```
feat(vim-ai): add user prompt for commit intention and refactor commit message generation

The vim-ai plugin now prompts the user to enter the intention of their 
commit, enhancing the creation of commit messages tailored to the 
user's changes. Additionally, the functionality for generating commit 
messages has been refactored, improving the interaction with GPT-4 AI. 
Code related to constructing a JSON message was removed, and
 new functions `askCommitIntention`, `getGitDiff`, and `buildPrompt`
 have been introduced to streamline the process. This commit aims
 to provide more professional and standardized commit messages,
 facilitating the automatic generation of release notes.
```

Please review and consider integrating this new custom command into the repository to enhance the commit message quality and streamline the release notes generation process.

**Comment by marcelarie** [comment]
Really nice, I added this to my personal config with a small change:
```diff
    .. "- Add line breaks at collumn 78"
+   .. "- Try to use 40 characters or less for the body of the commit message if the diff is small"
```

it would be nice to use a number to measure what is a small diff, but for now this works for me.

**Comment by marcelarie** [comment]
btw there is a typo in:
```
      "- All explanation must be inside the commit message. Do not write" ..
      " anything before or affter." ..
```

`affter` should be `after`

**Comment by marcelarie** [comment]
After updating to `v0.10.0-dev-2466+gcb146cc4a` I get this error:

```
Error executing Lua callback: /Users/m.manzanares/.config/nvim/lua/plugins/vim-ai.lua:82: function vim_ai#AIRun[1]..vim_ai_config#Extend
Deep, line 2: Vim(for):E715: Dictionary required
stack traceback:
        [C]: in function 'nvim_call_function'
        /Users/m.manzanares/.config/nvim/lua/plugins/vim-ai.lua:82: in function </Users/m.manzanares/.config/nvim/lua/plugins/vim-ai.lua:59>
```

**Comment by Konfekt** [comment]
Now `vim_ai#AIRun` dispenses with the `range` parameter. Use

> vim.api.nvim_call_function('vim_ai#AIRun', { config, prompt })

instead of

> vim.api.nvim_call_function('vim_ai#AIRun', { range, config, prompt })

**Comment by Konfekt** [comment]
I have updated the wiki accordingly as well

**Comment by Konfekt** [comment]
Both functions `vim_ai#AIRun/Edit` dropped the range parameter, whereas `vim_ai#AIChat` kept it since it does not operate on the current line by default

**Comment by marcelarie** [comment]
> Both functions `vim_ai#AIRun/Edit` dropped the range parameter, whereas `vim_ai#AIChat` kept it since it does not operate on the current line by default. Please check the updated documentation 

thanks!

**Comment by Konfekt** [comment]
By the way, [instructing ChatGPT](https://gist.github.com/Konfekt/cd194794fc76efe8a372892eb4312eaf) to write pertinent commit messages is an art in itself

**Comment by marcelarie** [comment]
Seems that the gist link is broken, is it [this](https://gist.github.com/Konfekt/d9640c390deea4beafcf74e29410b8a6) one?

**Comment by Konfekt** [comment]
Thank you, yes indeed. I fixed the URL in my comment

**Comment by madox2** [comment]
Please add [custom commands](https://github.com/madox2/vim-ai/wiki/Custom-commands) on the wiki. Also keep in mind that this plugin should be compatible for both vim and neovim.
