### ISSUE TITLE
handle ranges other than visual selection

### ISSUE THREAD

**Issue by Konfekt** [madox2/vim-ai#76]
When trying to pass, say the whole buffer, by `%AIEdit`, then instead only the last visual selection is passed.
The range logic seems odd to me. 
For example, if a range is passed then it is replaced by the visual selection and if a current line, then all lines in the range? 
Why is `<range>` needed on top of `<line1>` and `<line2>` ?

```vim
" autoload/vim_ai.vim (lines 90-96)
function! s:GetCurrentLineOrSelection(is_selection)
  if a:is_selection
    return s:GetVisualSelection()
  else
    return trim(join(getline(a:firstline, a:lastline), "\n"))
  endif
endfunction
```

**Comment by Konfekt** [comment]
More concretely, how about passing the line numbers instead of the `selection` parameter in all autoload functions? Then a non-default range was passed when `line1 != line2`.

**Comment by Konfekt** [comment]
It gets a bit more confusing in https://github.com/madox2/vim-ai/wiki/Custom-commands#add-programming-language-to-the-prompt where a custom range is replaced by the visual selection. Why are the line numbers are not simply passed on to `call vim_ai#AIRun(a:range, {}, l:instruction)`?

**Comment by Konfekt** [comment]
I wonder why neither the function has a final `range` attribute nor its invocations pass the ranges?

```vim
" autoload/vim_ai.vim (lines 90-96)
function! s:GetCurrentLineOrSelection(is_selection)
  if a:is_selection
    return s:GetVisualSelection()
  else
    return trim(join(getline(a:firstline, a:lastline), "\n"))
  endif
endfunction
```

and its invocations

```vim
" autoload/vim_ai.vim (lines 153-157)
function! vim_ai#AIEditRun(is_selection, config, ...) range
  let l:config = vim_ai_config#ExtendDeep(g:vim_ai_edit, a:config)

  let l:instruction = a:0 ? a:1 : ""
  let l:selection = s:GetCurrentLineOrSelection(a:is_selection)
```

and 

```vim
" autoload/vim_ai.vim (lines 123-127)
function! vim_ai#AIRun(is_selection, config, ...) range
  let l:config = vim_ai_config#ExtendDeep(g:vim_ai_complete, a:config)

  let l:instruction = a:0 ? a:1 : ""
  let l:selection = s:GetCurrentLineOrSelection(a:is_selection)
```

**Comment by madox2** [comment]
I am not quite sure what are you trying to accomplish. When you say `trying to pass, say the whole buffer`, do you mean passing text as an argument to the `vim_ai#AIEditRun` function?

**Comment by Konfekt** [comment]
`:AIEdit` accepts a range as it was defined by `command -range ...`; for example the last visual selection by `'<,'>AIEdit`, but also the whole buffer by `%AIEdit`, say for summarization, code review, .... (See `:help range` for the possible ranges). However, till now, every range is replaced by the last visual selection. For example, when opening a file and trying to summarize it by `:%AIEdit summarize`, then `:AIEdit` receives no input and does not summarize anything.

**Comment by Konfekt** [comment]
If you want to check if a range was passed, then you can use `command -range=0` and pass `<count>` as explained [here](https://stackoverflow.com/a/20133772). In any event, this check should be hidden away from the user of the `vim_ai#AI` functions instead of having to pass it as a first argument. See https://github.com/madox2/vim-ai/pull/77 for a suggestion

**Comment by madox2** [comment]
I wasn't thinking about using it this way - `:%AIEdit summarize`, but it looks like a great idea!

**Comment by madox2** [comment]
Actually this has been adressed in #77
