### ISSUE TITLE
feature request: enable wrap by default in the chat split

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [madox2/vim-ai#8]
I know very little about vimscript so I figured you would prefer to have the feature requests neatly organised by issues :)

**Comment by madox2** [comment]
Hi, do you mean `:set wrap` specifically?

**Comment by thiswillbeyourgithub** [comment]
You know vimscript better than me so I don't know if there are other ways but wrapping text seems indispensible for a lot of chat use. The LLM tends to go on long sentences explaining its code etc

**Comment by madox2** [comment]
I agree, please try using `:setlocal wrap` in the chat window and let me know if that's what you would expect

**Comment by thiswillbeyourgithub** [comment]
It is thanks

**Comment by madox2** [comment]
Hi, you can now set your wrapping preference using the `open_chat_command` configuration, e.g.:

```vim
let g:vim_ai_chat = {
\  "ui": {
\    "open_chat_command": "tabnew | setlocal wrap | call vim_ai#MakeScratchWindow()",
\  },
\}
```
