### ISSUE TITLE
Add Anthropic support

### ISSUE THREAD

**Issue by atmosx** [madox2/vim-ai#86]
The plugin seems to support just openAI GPT. Would be great to support anthropic, mistral and other AI providers as well.

**Comment by madox2** [comment]
Right, there is currently no built-in support for other AI providers. However it is possible to configure plugin with any OpenAI-compatible API. There are currently many projects providing OpenAI compatible proxies to all kinds of LLMs, such as [littlellm](https://github.com/BerriAI/litellm) and other, see [Custom APIs](https://github.com/madox2/vim-ai/wiki/Custom-APIs) on Wiki.
