### ISSUE TITLE
Question: Is it possible to configure vim-ai to use Copilot chat?

### ISSUE THREAD

**Issue by atsiporu** [madox2/vim-ai#90]
Is it possible to configure vim-ai to use Copilot chat?

**Comment by madox2** [comment]
This plugin is currently possible to configure with OpenAI-competible http endpoints. Does Copilot chat expose http API?

**Comment by atsiporu** [comment]
I know it exposes https://api.githubcopilot.com/chat/completions for the chat endpoint.
Not sure if it's Chat GPT compatible though

**Comment by madox2** [comment]
Is there any documentation on the API?

**Comment by RomaLzhih** [comment]
Yes it really good and useful to add the option for copilot chat

**Comment by RomaLzhih** [comment]
> Is there any documentation on the API?

A possible [method](https://github.com/yetone/avante.nvim/blob/main/lua/avante/providers/copilot.lua) to obtain the API from the neovim plugin `copilot.lua`.

**Comment by madox2** [comment]
If you find openai compatible proxy to copilot chat it should work with vim-ai. But the chance is small if they don't expose public API. Closing
