### ISSUE TITLE
What is sent to the LLM?

### ISSUE THREAD

**Issue by cduk** [madox2/vim-ai#92]
When I do a command such as: ":%AI write a letter based on this selection". How is the prompt constructed?

Is it something like:

"context <contents of %>
write a letter based on this selection"

I'm not sure if it is all just concatenated and put into the prompt, or some put in some other context (e.g. system prompt). I'm trying to understand to better construct my prompts. Thanks!

**Comment by Konfekt** [comment]
According to

```vim
" autoload/vim_ai.vim (line 67)
function! s:MakePrompt(selection, instruction, config)
...
let l:delimiter = l:instruction != "" && a:selection != "" ? ":\n" : ""
return join([l:instruction, l:delimiter, l:selection], "")
```

first the instruction, then a line break, then the selection is appended.

In

```py
#  py/complete.py (lines 36-39)
def chat_engine(prompt):
    initial_prompt = config_options.get('initial_prompt', [])
    initial_prompt = '\n'.join(initial_prompt)
    chat_content = f"{initial_prompt}\n\n>>> user\n\n{prompt}".strip()
```

the initial_prompt is prepended to this.

So the selection seems to be sent last.

**Comment by madox2** [comment]
Prompt that contains selection is constructed in this way: `{instruction}:/n{selection}`.

So in your case the prompt would be : `write a letter based on this selection:/n{selection}`

System prompt is possible only in chat endpoints and can be statically configured via `vim_ai_chat['options']['initial_prompt']`

You can also inspect all requests in the debug mode:

```vim
let g:vim_ai_debug = 0
let g:vim_ai_debug_log_file = "/tmp/vim_ai_debug.log"
```
